### PR TITLE
Add `Bulgarian` translation

### PR DESCRIPTION
**Pull request by YDu8VchU**

### CODE REVIEW

**Comment by cl8n** [comment]
hi, haven't tested these yet but I notice `description` is included for each message-- did you use https://loved.sh/localization to make these or copy en.json and go from there?

either works I guess, just wondering if there was something wrong with https://loved.sh/localization

**Comment by cl8n** [comment]
tried it out now, I can't review the language but seems all working and such. there are some places where the length of text causes layout issues, here I noticed the options above the submissions table and the site header having some odd wrapping. if it's possible to fix those I think it'd look better, but if not that's fine--- some other languages have the same issue so it may be worth changing the layout there anyway.

thanks for translation 🎉

**Comment by YDu8VchU** [comment]
I created a clone with github desktop and didnt notice the description. Im not using the tool from website because is not that easy to save my progress and continue later. I will check and try to do something about the submissions table.

**Comment by cl8n** [comment]
oh right... forgot I never added anything to continue in-progress translation
tracking as the last item of #69

**Pull request merged**
